spring:
  message: Hello world from production environment
  datasource:
    username: root
    password: Vinhanh123
    url: jdbc:mysql://localhost:3306/sb?useSSL=false&characterEncoding=UTF-8
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
  
## profile specific port.
server:
  port: 10093

