spring:
  message: Hello world from dev environment
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Vinhanh123
    url: jdbc:mysql://localhost:3306/spring?useSSL=false&characterEncoding=UTF-8
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
  
## profile specific port.
server:
  port: 10091